server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:practice
    #    jdbc:h2:tcp://localhost/~/Desktop/h2-2022-06-13/h2/bin/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true

logging:
  level:
    org.springframework:
      messaging: trace
      web:
        socket: trace
